Updated script boilerplate for consistency

diff --git a/wsh/bin/git-clone-with-path b/wsh/bin/git-clone-with-path
--- a/wsh/bin/git-clone-with-path
+++ b/wsh/bin/git-clone-with-path
@@ -1,4 +1,29 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+##############################################################################
+# Shell Behaviour
+##############################################################################
+
+# Check for unbound variables being used
+# set -o nounset
+
+# Exit is a bad command is attempted. If you're going to handle errors then
+# leave this disabled
+# set -o errexit
+
+# Exit if any of the commands in a pipeline exit with a non-zero exit code
+# set -o pipefail
+
+##############################################################################
+# Variables
+##############################################################################
+
+CONST_COMMAND_LINE="$@"
+CONST_OS_VERSION=$(uname -r)
+CONST_SYSTEM_TYPE=$(uname -m)
+CONST_SCRIPT_NAME=${0##*/}
+CONST_SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+
 # Attempts to clone the given Git repo to a corresponding relative path directory
 function _git_clone_with_path() {
     # Check if the argument is provided
